version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/my-app/app
    ports:
      - "3200:3200"
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3200
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
